### ISSUE TITLE
User Account - Implementation

### ISSUE THREAD

**Issue by EDsteve** [EDsteve/ELOC-Control-Panel#9]
Sign up with
- [x] email/password
- [x] Google

Sign in with
- [x] email/password
- [x] Google

User profile
- [x] Set profile picture
- [x] Set display name
- [x] Set ranger ID to be used with ELOC device

Management
- [x] Change email
- [x] Change password
- [x] Delete account

**Comment by EDsteve** [comment]
@josephx86 
Just for the record: We have decided to make the Ranger ID into User ID. That's more universal.
So  guess User ID is the same with "display name" of the user account?

**Comment by josephx86** [comment]
The idea for the display name is that it is the name displayed on the profile. Ranger ID (now User ID) on the other hand, is for the ELOC devices to use.
